name: Sync to Bitbucket

on:
  push:
    branches:
      - develop

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Push to Bitbucket via token
        run: |
          git config user.name "GitHub Sync Bot"
          git config user.email "${{ secrets.BB_BOT_EMAIL }}"

          git remote add bitbucket https://x-token-auth:${{ secrets.BB_TOKEN }}@bitbucket.org/udn_devolopers/githubsynctest.git

          git push --mirror bitbucket
